[2025-05-28T05:22:40.981+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-28T05:22:41.014+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:22:38.546586+00:00 [queued]>
[2025-05-28T05:22:41.031+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:22:38.546586+00:00 [queued]>
[2025-05-28T05:22:41.031+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-05-28T05:22:41.062+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_street_food_analysis> on 2025-05-28 05:22:38.546586+00:00
[2025-05-28T05:22:41.076+0000] {standard_task_runner.py:72} INFO - Started process 517 to run task
[2025-05-28T05:22:41.080+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'global_street_food_analysis_dag', 'run_street_food_analysis', 'manual__2025-05-28T05:22:38.546586+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/global_food.py', '--cfg-path', '/tmp/tmpw9l2ceic']
[2025-05-28T05:22:41.083+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask run_street_food_analysis
[2025-05-28T05:22:41.311+0000] {task_command.py:467} INFO - Running <TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:22:38.546586+00:00 [running]> on host 6041824b4dd1
[2025-05-28T05:22:41.683+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='global_street_food_analysis_dag' AIRFLOW_CTX_TASK_ID='run_street_food_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T05:22:38.546586+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T05:22:38.546586+00:00'
[2025-05-28T05:22:41.700+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-28T05:22:41.956+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-28T05:22:41.973+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/airflow/scripts/food.py']
[2025-05-28T05:22:41.983+0000] {subprocess.py:86} INFO - Output:
[2025-05-28T05:22:50.844+0000] {subprocess.py:93} INFO - 25/05/28 05:22:50 INFO SparkContext: Running Spark version 3.5.5
[2025-05-28T05:22:50.852+0000] {subprocess.py:93} INFO - 25/05/28 05:22:50 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:22:50.854+0000] {subprocess.py:93} INFO - 25/05/28 05:22:50 INFO SparkContext: Java version 17.0.15
[2025-05-28T05:22:51.045+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-28T05:22:51.279+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO ResourceUtils: ==============================================================
[2025-05-28T05:22:51.281+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-28T05:22:51.282+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO ResourceUtils: ==============================================================
[2025-05-28T05:22:51.282+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO SparkContext: Submitted application: GlobalStreetFoodAnalysis
[2025-05-28T05:22:51.338+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-28T05:22:51.358+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO ResourceProfile: Limiting resource is cpu
[2025-05-28T05:22:51.359+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-28T05:22:51.524+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO SecurityManager: Changing view acls to: airflow
[2025-05-28T05:22:51.524+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-28T05:22:51.525+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO SecurityManager: Changing view acls groups to:
[2025-05-28T05:22:51.527+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO SecurityManager: Changing modify acls groups to:
[2025-05-28T05:22:51.528+0000] {subprocess.py:93} INFO - 25/05/28 05:22:51 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-05-28T05:22:52.482+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO Utils: Successfully started service 'sparkDriver' on port 46867.
[2025-05-28T05:22:52.545+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO SparkEnv: Registering MapOutputTracker
[2025-05-28T05:22:52.628+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-28T05:22:52.678+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-28T05:22:52.679+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-28T05:22:52.689+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-28T05:22:52.729+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-ab274320-ce89-4f16-b80e-17e191d23b8f
[2025-05-28T05:22:52.759+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-28T05:22:52.787+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-28T05:22:52.978+0000] {subprocess.py:93} INFO - 25/05/28 05:22:52 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-05-28T05:22:53.189+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-28T05:22:53.641+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO Executor: Starting executor ID driver on host 6041824b4dd1
[2025-05-28T05:22:53.642+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:22:53.643+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO Executor: Java version 17.0.15
[2025-05-28T05:22:53.672+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-05-28T05:22:53.674+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5440f362 for default.
[2025-05-28T05:22:53.724+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46713.
[2025-05-28T05:22:53.725+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO NettyBlockTransferService: Server created on 6041824b4dd1:46713
[2025-05-28T05:22:53.730+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-28T05:22:53.742+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 6041824b4dd1, 46713, None)
[2025-05-28T05:22:53.755+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO BlockManagerMasterEndpoint: Registering block manager 6041824b4dd1:46713 with 434.4 MiB RAM, BlockManagerId(driver, 6041824b4dd1, 46713, None)
[2025-05-28T05:22:53.760+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 6041824b4dd1, 46713, None)
[2025-05-28T05:22:53.762+0000] {subprocess.py:93} INFO - 25/05/28 05:22:53 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 6041824b4dd1, 46713, None)
[2025-05-28T05:22:55.031+0000] {subprocess.py:93} INFO - 25/05/28 05:22:55 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-28T05:22:55.077+0000] {subprocess.py:93} INFO - 25/05/28 05:22:55 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp1dfv9jkh/spark-warehouse'.
[2025-05-28T05:22:59.244+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-28T05:22:59.245+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/food.py", line 10, in <module>
[2025-05-28T05:22:59.245+0000] {subprocess.py:93} INFO -     df = spark.read.csv("/opt/airflow/global_street_food.csv", header=True, inferSchema=True)
[2025-05-28T05:22:59.245+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-05-28T05:22:59.246+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-28T05:22:59.246+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-05-28T05:22:59.262+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/global_street_food.csv.
[2025-05-28T05:22:59.354+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO SparkContext: Invoking stop() from shutdown hook
[2025-05-28T05:22:59.354+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-05-28T05:22:59.374+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO SparkUI: Stopped Spark web UI at http://6041824b4dd1:4040
[2025-05-28T05:22:59.391+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-28T05:22:59.458+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO MemoryStore: MemoryStore cleared
[2025-05-28T05:22:59.458+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO BlockManager: BlockManager stopped
[2025-05-28T05:22:59.473+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-28T05:22:59.477+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-28T05:22:59.508+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO SparkContext: Successfully stopped SparkContext
[2025-05-28T05:22:59.509+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO ShutdownHookManager: Shutdown hook called
[2025-05-28T05:22:59.510+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-e04bc981-3518-4aa0-936b-c905a99142f7
[2025-05-28T05:22:59.539+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-5a9c92e5-1e5b-4282-a929-10da0fc04425
[2025-05-28T05:22:59.570+0000] {subprocess.py:93} INFO - 25/05/28 05:22:59 INFO ShutdownHookManager: Deleting directory /tmp/spark-5a9c92e5-1e5b-4282-a929-10da0fc04425/pyspark-e5bf40eb-db68-4242-9409-9175b80afefb
[2025-05-28T05:22:59.678+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-28T05:22:59.740+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:22:59.763+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=global_street_food_analysis_dag, task_id=run_street_food_analysis, run_id=manual__2025-05-28T05:22:38.546586+00:00, execution_date=20250528T052238, start_date=20250528T052241, end_date=20250528T052259
[2025-05-28T05:22:59.805+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-28T05:22:59.807+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task run_street_food_analysis (Bash command failed. The command returned a non-zero exit code 1.; 517)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:22:59.844+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-28T05:22:59.878+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-28T05:22:59.880+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
