[2025-05-28T05:19:11.079+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-28T05:19:11.352+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:19:06.936470+00:00 [queued]>
[2025-05-28T05:19:11.374+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:19:06.936470+00:00 [queued]>
[2025-05-28T05:19:11.374+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-05-28T05:19:11.424+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_street_food_analysis> on 2025-05-28 05:19:06.936470+00:00
[2025-05-28T05:19:11.440+0000] {standard_task_runner.py:72} INFO - Started process 321 to run task
[2025-05-28T05:19:11.469+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'global_street_food_analysis_dag', 'run_street_food_analysis', 'manual__2025-05-28T05:19:06.936470+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/global_food.py', '--cfg-path', '/tmp/tmp8uh16th4']
[2025-05-28T05:19:11.478+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask run_street_food_analysis
[2025-05-28T05:19:11.827+0000] {task_command.py:467} INFO - Running <TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:19:06.936470+00:00 [running]> on host 6041824b4dd1
[2025-05-28T05:19:12.171+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='global_street_food_analysis_dag' AIRFLOW_CTX_TASK_ID='run_street_food_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T05:19:06.936470+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T05:19:06.936470+00:00'
[2025-05-28T05:19:12.175+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-28T05:19:12.255+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-28T05:19:12.257+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/airflow/scripts/food.py']
[2025-05-28T05:19:12.274+0000] {subprocess.py:86} INFO - Output:
[2025-05-28T05:19:27.444+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 INFO SparkContext: Running Spark version 3.5.5
[2025-05-28T05:19:27.448+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:19:27.448+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 INFO SparkContext: Java version 17.0.15
[2025-05-28T05:19:27.640+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-28T05:19:27.975+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 INFO ResourceUtils: ==============================================================
[2025-05-28T05:19:27.976+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-28T05:19:27.977+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 INFO ResourceUtils: ==============================================================
[2025-05-28T05:19:27.978+0000] {subprocess.py:93} INFO - 25/05/28 05:19:27 INFO SparkContext: Submitted application: GlobalStreetFoodAnalysis
[2025-05-28T05:19:28.031+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-28T05:19:28.045+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO ResourceProfile: Limiting resource is cpu
[2025-05-28T05:19:28.047+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-28T05:19:28.279+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO SecurityManager: Changing view acls to: airflow
[2025-05-28T05:19:28.282+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-28T05:19:28.285+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO SecurityManager: Changing view acls groups to:
[2025-05-28T05:19:28.316+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO SecurityManager: Changing modify acls groups to:
[2025-05-28T05:19:28.330+0000] {subprocess.py:93} INFO - 25/05/28 05:19:28 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-05-28T05:19:29.098+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO Utils: Successfully started service 'sparkDriver' on port 45687.
[2025-05-28T05:19:29.261+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO SparkEnv: Registering MapOutputTracker
[2025-05-28T05:19:29.381+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-28T05:19:29.424+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-28T05:19:29.426+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-28T05:19:29.439+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-28T05:19:29.530+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-37c97683-ed64-49dc-8338-e635e130852b
[2025-05-28T05:19:29.557+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-28T05:19:29.592+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-28T05:19:29.885+0000] {subprocess.py:93} INFO - 25/05/28 05:19:29 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-05-28T05:19:30.113+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-28T05:19:30.610+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO Executor: Starting executor ID driver on host 6041824b4dd1
[2025-05-28T05:19:30.611+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-28T05:19:30.611+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO Executor: Java version 17.0.15
[2025-05-28T05:19:30.630+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-05-28T05:19:30.631+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5440f362 for default.
[2025-05-28T05:19:30.712+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46615.
[2025-05-28T05:19:30.713+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO NettyBlockTransferService: Server created on 6041824b4dd1:46615
[2025-05-28T05:19:30.716+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-28T05:19:30.745+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 6041824b4dd1, 46615, None)
[2025-05-28T05:19:30.759+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO BlockManagerMasterEndpoint: Registering block manager 6041824b4dd1:46615 with 434.4 MiB RAM, BlockManagerId(driver, 6041824b4dd1, 46615, None)
[2025-05-28T05:19:30.768+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 6041824b4dd1, 46615, None)
[2025-05-28T05:19:30.775+0000] {subprocess.py:93} INFO - 25/05/28 05:19:30 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 6041824b4dd1, 46615, None)
[2025-05-28T05:19:33.116+0000] {subprocess.py:93} INFO - 25/05/28 05:19:33 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-28T05:19:33.343+0000] {subprocess.py:93} INFO - 25/05/28 05:19:33 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpka4n43hg/spark-warehouse'.
[2025-05-28T05:19:36.279+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-28T05:19:36.279+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/food.py", line 10, in <module>
[2025-05-28T05:19:36.280+0000] {subprocess.py:93} INFO -     df = spark.read.csv("/home/sreelakshmi/pyspark_airflow/global_street_food.csv", header=True, inferSchema=True)
[2025-05-28T05:19:36.280+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-05-28T05:19:36.280+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-28T05:19:36.280+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-05-28T05:19:36.294+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/home/sreelakshmi/pyspark_airflow/global_street_food.csv.
[2025-05-28T05:19:36.392+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO SparkContext: Invoking stop() from shutdown hook
[2025-05-28T05:19:36.393+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-05-28T05:19:36.410+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO SparkUI: Stopped Spark web UI at http://6041824b4dd1:4040
[2025-05-28T05:19:36.432+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-28T05:19:36.475+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO MemoryStore: MemoryStore cleared
[2025-05-28T05:19:36.476+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO BlockManager: BlockManager stopped
[2025-05-28T05:19:36.482+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-28T05:19:36.489+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-28T05:19:36.508+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO SparkContext: Successfully stopped SparkContext
[2025-05-28T05:19:36.508+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO ShutdownHookManager: Shutdown hook called
[2025-05-28T05:19:36.509+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO ShutdownHookManager: Deleting directory /tmp/spark-1d15b0b5-f2f6-4018-9547-954345162585
[2025-05-28T05:19:36.514+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO ShutdownHookManager: Deleting directory /tmp/spark-2f7aa4fb-f54d-4258-8644-66ce4c1f7a69
[2025-05-28T05:19:36.524+0000] {subprocess.py:93} INFO - 25/05/28 05:19:36 INFO ShutdownHookManager: Deleting directory /tmp/spark-2f7aa4fb-f54d-4258-8644-66ce4c1f7a69/pyspark-ae98dc7d-ae2e-4c16-83c1-4265b2bc83a7
[2025-05-28T05:19:36.574+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-28T05:19:36.592+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:19:36.629+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=global_street_food_analysis_dag, task_id=run_street_food_analysis, run_id=manual__2025-05-28T05:19:06.936470+00:00, execution_date=20250528T051906, start_date=20250528T051911, end_date=20250528T051936
[2025-05-28T05:19:36.673+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-28T05:19:36.674+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task run_street_food_analysis (Bash command failed. The command returned a non-zero exit code 1.; 321)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-28T05:19:36.719+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-28T05:19:36.751+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-28T05:19:36.755+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
